#!/usr/bin/env bash
set -eu
if [ $# -lt 1 ]; then
   echo "$0 patternid [[text]|[-primary text] [-clip text] [-argv arg]]" 
   exit 1
fi

# plum_debug_section line:ag "readme.md:30"
# plum_debug_section line:ag -primary "readme.md" -clip "notused" -argv dragon 

export PLUM_DEBUG=99
export PLUM_ECHO=1 
export PLUM_DEBUGID="$1"; shift

while [ $# -gt 0 ]; do
   case "$1" in 
    -argv) 
       shift
       plum "$1"
       exit
       ;;
    -clip)
       shift
       echo "$1" | xclip -i -selection clipboard
       shift
       ;;
    -primary)
       shift
       echo "$1" | xclip -i
       shift
       ;;
    *)
       echo "$@" | xclip -i
       break
       ;;
   esac
done

# try it
plum 
