#!/usr/bin/env bash

dzen_menu_cmd(){
 # get x,y mouse pointer position
 read  XP YP <<< $(getcurpos)
  
 # N.B. YP-25 might be too high 
 [ -z "$1" ] && ydelta=25 || ydelta=$1
 dzen2 -y $((($YP-$ydelta))) -x "$((($XP-10)))" -l 3 -w 300 -m -p -e 'onstart=uncollapse;button1=menuexec;leaveslave=exit;button3=exit;'
}

rofi_menu_cmd(){
   rofi -dmenu -m -3 -yoffset -35 -xoffset -10 | # -me-select-entry '' -me-accept-entry 'Mouse1'
      xargs -0ri sh -c "plum '{}'"
}

cat <<EOF | rofi_menu_cmd

search
x|dragon
x|xmessage
|xargs -0r xmessage
<tr '[a-z]' '[A-Z]'
ssh s pbpaste>
EOF
